---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
#Mi primer markdown para ggplot2

##configuraciones

```{r misconf, include=FALSE}
 setwd("~/federico")
install.packages("treemap")
install.packages("tidyverse")
install.packages("openair")
install.packages("quantmod")
install.packages("readxl")
install.packages("lubridate")


library("treemap")
library("tidyverse")
library("openair")
library("quantmod")
library("readxl")
library("lubridate")

```

## Gramatica de Código

```{r gramatica, echo=FALSE}
ggplot(data=diamonds, aes(x=carat,y=price))+
  geom_point()+
  stat_smooth(method=lm)+
  scale_x_log10()+
  scale_y_log10()
```


```{r hello plot}
ggplot(data=mpg)+
  geom_point(mapping=aes (x=displ, y=hwy))+
  xlab("tamaño del motor")+
  ylab("efeciencia del carro en carretera")

```
```{r hello plot}
ggplot(data=mpg)+
  geom_point(mapping=aes (x=cyl, y=hwy))+
  xlab("tamaño del motor")+
  ylab("efeciencia del carro en carretera")

```

```{r hello plot}
ggplot(data=mpg)+
  geom_point(mapping=aes (x=class, y=drv))+
  xlab("tamaño del motor")+
  ylab("efeciencia del carro en carretera")

```


```{r hello plot, echo=FALSE}
ggplot(data=mpg)+
  geom_point(mapping=aes (x=displ, y=hwy, size= cyl, color=class, alpha=class, ))+
  facet_wrap(~ class,nrow=)

 
```
```{r hello plot, echo=FALSE}
ggplot(data=mpg)+
  geom_point(mapping=aes (x=displ, y=hwy, size= cyl, color=class, alpha=class, shape=class))+
  facet_grid(.~ cyl)

 
```
```{r hello plot, echo=FALSE}
ggplot(data=mpg)+
  geom_point(mapping=aes (x=displ, y=hwy, size= cyl, color=class, alpha=class, shape=class))+
  facet_grid(.~ displ)

 
```




```{r hello plot, echo=FALSE}
ggplot(data=mpg)+
  geom_smooth(mapping=aes (x=displ, y=hwy, size= cyl, color=class, linetype=drv, shape=class))
  

```

```{r hello plot, echo=FALSE}
ggplot(data=mpg)+
  geom_smooth(mapping=aes (x=displ, y=hwy, size= cyl, color=class, linetype=drv, shape=class))
  
```



```{r hello plot, echo=FALSE}
ggplot(data=diamonds)+
  stat_summary( mapping= aes( cut,table))
geom_bar(mapping=aes(x=cut,colour=cut))
  
```

